# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addrepodialog.ui'
#
# Created: Wed Apr 02 10:42:47 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_AddRepoDialog(object):
    def setupUi(self, AddRepoDialog):
        AddRepoDialog.setObjectName(_fromUtf8("AddRepoDialog"))
        AddRepoDialog.resize(425, 361)
        AddRepoDialog.setStyleSheet(_fromUtf8("#addRepoDialog {\n"
"    background-color: #eeeeee;\n"
"}"))
        self.verticalLayout = QtGui.QVBoxLayout(AddRepoDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.addRepoLabel = QtGui.QLabel(AddRepoDialog)
        self.addRepoLabel.setObjectName(_fromUtf8("addRepoLabel"))
        self.horizontalLayout_3.addWidget(self.addRepoLabel)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.addRepoFolderBox = QtGui.QLineEdit(AddRepoDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addRepoFolderBox.sizePolicy().hasHeightForWidth())
        self.addRepoFolderBox.setSizePolicy(sizePolicy)
        self.addRepoFolderBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.addRepoFolderBox.setText(_fromUtf8(""))
        self.addRepoFolderBox.setObjectName(_fromUtf8("addRepoFolderBox"))
        self.horizontalLayout_4.addWidget(self.addRepoFolderBox)
        self.selectRepoFolderButton = QtGui.QToolButton(AddRepoDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectRepoFolderButton.sizePolicy().hasHeightForWidth())
        self.selectRepoFolderButton.setSizePolicy(sizePolicy)
        self.selectRepoFolderButton.setMinimumSize(QtCore.QSize(0, 21))
        self.selectRepoFolderButton.setMaximumSize(QtCore.QSize(16777215, 16677215))
        self.selectRepoFolderButton.setObjectName(_fromUtf8("selectRepoFolderButton"))
        self.horizontalLayout_4.addWidget(self.selectRepoFolderButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.cloneCheckBox = QtGui.QCheckBox(AddRepoDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cloneCheckBox.sizePolicy().hasHeightForWidth())
        self.cloneCheckBox.setSizePolicy(sizePolicy)
        self.cloneCheckBox.setStyleSheet(_fromUtf8("#copyLabel {\n"
"  color: #666666;\n"
"}"))
        self.cloneCheckBox.setObjectName(_fromUtf8("cloneCheckBox"))
        self.horizontalLayout_7.addWidget(self.cloneCheckBox)
        self.cloneFolderBox = QtGui.QLineEdit(AddRepoDialog)
        self.cloneFolderBox.setObjectName(_fromUtf8("cloneFolderBox"))
        self.horizontalLayout_7.addWidget(self.cloneFolderBox)
        self.selectCloneFolderButton = QtGui.QToolButton(AddRepoDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectCloneFolderButton.sizePolicy().hasHeightForWidth())
        self.selectCloneFolderButton.setSizePolicy(sizePolicy)
        self.selectCloneFolderButton.setMinimumSize(QtCore.QSize(0, 21))
        self.selectCloneFolderButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.selectCloneFolderButton.setObjectName(_fromUtf8("selectCloneFolderButton"))
        self.horizontalLayout_7.addWidget(self.selectCloneFolderButton)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.addRepoButton = QtGui.QPushButton(AddRepoDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addRepoButton.sizePolicy().hasHeightForWidth())
        self.addRepoButton.setSizePolicy(sizePolicy)
        self.addRepoButton.setMinimumSize(QtCore.QSize(133, 0))
        self.addRepoButton.setMaximumSize(QtCore.QSize(133, 32))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/add-repo-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addRepoButton.setIcon(icon)
        self.addRepoButton.setObjectName(_fromUtf8("addRepoButton"))
        self.horizontalLayout_2.addWidget(self.addRepoButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(AddRepoDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.line = QtGui.QFrame(AddRepoDialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_6 = QtGui.QLabel(AddRepoDialog)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_5.addWidget(self.label_6)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.createRepoFolderBox = QtGui.QLineEdit(AddRepoDialog)
        self.createRepoFolderBox.setText(_fromUtf8(""))
        self.createRepoFolderBox.setObjectName(_fromUtf8("createRepoFolderBox"))
        self.horizontalLayout_6.addWidget(self.createRepoFolderBox)
        self.selectNewRepoFolderButton = QtGui.QToolButton(AddRepoDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectNewRepoFolderButton.sizePolicy().hasHeightForWidth())
        self.selectNewRepoFolderButton.setSizePolicy(sizePolicy)
        self.selectNewRepoFolderButton.setMinimumSize(QtCore.QSize(0, 21))
        self.selectNewRepoFolderButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.selectNewRepoFolderButton.setObjectName(_fromUtf8("selectNewRepoFolderButton"))
        self.horizontalLayout_6.addWidget(self.selectNewRepoFolderButton)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.createRepoButton = QtGui.QPushButton(AddRepoDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createRepoButton.sizePolicy().hasHeightForWidth())
        self.createRepoButton.setSizePolicy(sizePolicy)
        self.createRepoButton.setMinimumSize(QtCore.QSize(133, 0))
        self.createRepoButton.setMaximumSize(QtCore.QSize(133, 111111))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/create-repo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.createRepoButton.setIcon(icon1)
        self.createRepoButton.setIconSize(QtCore.QSize(20, 16))
        self.createRepoButton.setObjectName(_fromUtf8("createRepoButton"))
        self.horizontalLayout_8.addWidget(self.createRepoButton)
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.createRepoAndImportButton = QtGui.QPushButton(AddRepoDialog)
        self.createRepoAndImportButton.setMinimumSize(QtCore.QSize(133, 0))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/create-and-import-repo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.createRepoAndImportButton.setIcon(icon2)
        self.createRepoAndImportButton.setIconSize(QtCore.QSize(20, 16))
        self.createRepoAndImportButton.setObjectName(_fromUtf8("createRepoAndImportButton"))
        self.horizontalLayout_8.addWidget(self.createRepoAndImportButton)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.line_2 = QtGui.QFrame(AddRepoDialog)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem6)
        self.buttonBox = QtGui.QDialogButtonBox(AddRepoDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setMinimumSize(QtCore.QSize(0, 32))
        self.buttonBox.setMaximumSize(QtCore.QSize(16777215, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_10.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_10)

        self.retranslateUi(AddRepoDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), AddRepoDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), AddRepoDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AddRepoDialog)

    def retranslateUi(self, AddRepoDialog):
        AddRepoDialog.setWindowTitle(_translate("AddRepoDialog", "Add or Create a Repository", None))
        self.addRepoLabel.setText(_translate("AddRepoDialog", "Add existing repository:", None))
        self.addRepoFolderBox.setPlaceholderText(_translate("AddRepoDialog", "Local or remote Versio repository location", None))
        self.selectRepoFolderButton.setText(_translate("AddRepoDialog", "...", None))
        self.cloneCheckBox.setText(_translate("AddRepoDialog", "Copy repository locally to:", None))
        self.selectCloneFolderButton.setText(_translate("AddRepoDialog", "...", None))
        self.addRepoButton.setText(_translate("AddRepoDialog", "Add repository", None))
        self.label.setText(_translate("AddRepoDialog", "OR", None))
        self.label_6.setText(_translate("AddRepoDialog", "Create new repository:", None))
        self.createRepoFolderBox.setPlaceholderText(_translate("AddRepoDialog", "Enter a location for the new repository", None))
        self.selectNewRepoFolderButton.setText(_translate("AddRepoDialog", "...", None))
        self.createRepoButton.setText(_translate("AddRepoDialog", "Create Repository", None))
        self.createRepoAndImportButton.setText(_translate("AddRepoDialog", "Create + Import", None))

import geogigclient_resources_rc
