# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'conflictDialog.ui'
#
# Created: Wed Dec 17 14:19:28 2014
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ConflictDialog(object):
    def setupUi(self, ConflictDialog):
        ConflictDialog.setObjectName(_fromUtf8("ConflictDialog"))
        ConflictDialog.resize(1029, 778)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ConflictDialog.sizePolicy().hasHeightForWidth())
        ConflictDialog.setSizePolicy(sizePolicy)
        ConflictDialog.setMinimumSize(QtCore.QSize(600, 700))
        self.verticalLayout_2 = QtGui.QVBoxLayout(ConflictDialog)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.widget = QtGui.QWidget(ConflictDialog)
        self.widget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.conflictsTree = QtGui.QTreeWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.conflictsTree.sizePolicy().hasHeightForWidth())
        self.conflictsTree.setSizePolicy(sizePolicy)
        self.conflictsTree.setMinimumSize(QtCore.QSize(200, 200))
        self.conflictsTree.setMaximumSize(QtCore.QSize(232131, 321321))
        self.conflictsTree.setAlternatingRowColors(True)
        self.conflictsTree.setUniformRowHeights(True)
        self.conflictsTree.setObjectName(_fromUtf8("conflictsTree"))
        self.verticalLayout_3.addWidget(self.conflictsTree)
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.solveAllTheirsButton = QtGui.QPushButton(self.widget)
        self.solveAllTheirsButton.setObjectName(_fromUtf8("solveAllTheirsButton"))
        self.horizontalLayout_3.addWidget(self.solveAllTheirsButton)
        self.solveAllOursButton = QtGui.QPushButton(self.widget)
        self.solveAllOursButton.setObjectName(_fromUtf8("solveAllOursButton"))
        self.horizontalLayout_3.addWidget(self.solveAllOursButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addWidget(self.widget)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_7 = QtGui.QLabel(ConflictDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_4.addWidget(self.label_7)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.solveButton = QtGui.QPushButton(ConflictDialog)
        self.solveButton.setEnabled(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/push-repo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.solveButton.setIcon(icon)
        self.solveButton.setIconSize(QtCore.QSize(16, 16))
        self.solveButton.setObjectName(_fromUtf8("solveButton"))
        self.horizontalLayout_4.addWidget(self.solveButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.splitter = QtGui.QSplitter(ConflictDialog)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.attributesTable = QtGui.QTableWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attributesTable.sizePolicy().hasHeightForWidth())
        self.attributesTable.setSizePolicy(sizePolicy)
        self.attributesTable.setMinimumSize(QtCore.QSize(250, 100))
        self.attributesTable.setMaximumSize(QtCore.QSize(1000, 150))
        self.attributesTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.attributesTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.attributesTable.setProperty("showDropIndicator", False)
        self.attributesTable.setDragDropOverwriteMode(False)
        self.attributesTable.setAlternatingRowColors(False)
        self.attributesTable.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.attributesTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.attributesTable.setShowGrid(True)
        self.attributesTable.setGridStyle(QtCore.Qt.DotLine)
        self.attributesTable.setWordWrap(False)
        self.attributesTable.setObjectName(_fromUtf8("attributesTable"))
        self.attributesTable.setColumnCount(4)
        self.attributesTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.attributesTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.attributesTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        item.setFont(font)
        item.setBackground(QtGui.QColor(0, 0, 0, 0))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.attributesTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.attributesTable.setHorizontalHeaderItem(3, item)
        self.attributesTable.horizontalHeader().setCascadingSectionResizes(True)
        self.attributesTable.horizontalHeader().setDefaultSectionSize(135)
        self.attributesTable.horizontalHeader().setMinimumSectionSize(30)
        self.attributesTable.horizontalHeader().setStretchLastSection(True)
        self.attributesTable.verticalHeader().setVisible(False)
        self.attributesTable.verticalHeader().setCascadingSectionResizes(False)
        self.attributesTable.verticalHeader().setStretchLastSection(False)
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_11.setMargin(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_10.addWidget(self.label_9)
        self.showOursCheck = QtGui.QCheckBox(self.layoutWidget)
        self.showOursCheck.setChecked(True)
        self.showOursCheck.setObjectName(_fromUtf8("showOursCheck"))
        self.horizontalLayout_10.addWidget(self.showOursCheck)
        self.showTheirsCheck = QtGui.QCheckBox(self.layoutWidget)
        self.showTheirsCheck.setChecked(True)
        self.showTheirsCheck.setObjectName(_fromUtf8("showTheirsCheck"))
        self.horizontalLayout_10.addWidget(self.showTheirsCheck)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_10.addWidget(self.label_2)
        self.baseMapCombo = QtGui.QComboBox(self.layoutWidget)
        self.baseMapCombo.setObjectName(_fromUtf8("baseMapCombo"))
        self.baseMapCombo.addItem(_fromUtf8(""))
        self.baseMapCombo.addItem(_fromUtf8(""))
        self.baseMapCombo.addItem(_fromUtf8(""))
        self.horizontalLayout_10.addWidget(self.baseMapCombo)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.zoomButton = QtGui.QToolButton(self.layoutWidget)
        self.zoomButton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/zoom-extent.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomButton.setIcon(icon1)
        self.zoomButton.setObjectName(_fromUtf8("zoomButton"))
        self.horizontalLayout_10.addWidget(self.zoomButton)
        self.verticalLayout_11.addLayout(self.horizontalLayout_10)
        self.canvasWidget = QtGui.QWidget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canvasWidget.sizePolicy().hasHeightForWidth())
        self.canvasWidget.setSizePolicy(sizePolicy)
        self.canvasWidget.setMinimumSize(QtCore.QSize(0, 300))
        self.canvasWidget.setObjectName(_fromUtf8("canvasWidget"))
        self.verticalLayout_11.addWidget(self.canvasWidget)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.verticalLayout_11.addLayout(self.horizontalLayout_13)
        self.verticalLayout.addWidget(self.splitter)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.buttonBox = QtGui.QDialogButtonBox(ConflictDialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(ConflictDialog)
        QtCore.QMetaObject.connectSlotsByName(ConflictDialog)

    def retranslateUi(self, ConflictDialog):
        ConflictDialog.setWindowTitle(_translate("ConflictDialog", "Merge Conflicts", None))
        self.conflictsTree.headerItem().setText(0, _translate("ConflictDialog", "Conflicts", None))
        self.label.setText(_translate("ConflictDialog", "Resolve All Conflicts with:", None))
        self.solveAllTheirsButton.setText(_translate("ConflictDialog", "To merge", None))
        self.solveAllOursButton.setText(_translate("ConflictDialog", "Local", None))
        self.label_7.setText(_translate("ConflictDialog", "Click on a value cell to use it in the merged feature:", None))
        self.solveButton.setText(_translate("ConflictDialog", "Solve", None))
        self.attributesTable.setSortingEnabled(True)
        item = self.attributesTable.horizontalHeaderItem(0)
        item.setText(_translate("ConflictDialog", "Local", None))
        item = self.attributesTable.horizontalHeaderItem(1)
        item.setText(_translate("ConflictDialog", "To merge", None))
        item = self.attributesTable.horizontalHeaderItem(2)
        item.setText(_translate("ConflictDialog", "ATTRIBUTES", None))
        item = self.attributesTable.horizontalHeaderItem(3)
        item.setText(_translate("ConflictDialog", "Merged", None))
        self.label_9.setText(_translate("ConflictDialog", "Show:", None))
        self.showOursCheck.setText(_translate("ConflictDialog", "Local", None))
        self.showTheirsCheck.setText(_translate("ConflictDialog", "To merge", None))
        self.label_2.setText(_translate("ConflictDialog", "Base Map:", None))
        self.baseMapCombo.setItemText(0, _translate("ConflictDialog", "None", None))
        self.baseMapCombo.setItemText(1, _translate("ConflictDialog", "OpenStreetMap", None))
        self.baseMapCombo.setItemText(2, _translate("ConflictDialog", "Google Maps", None))

import geogigclient_resources_rc
