# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mergedialog.ui'
#
# Created: Fri May 30 09:15:18 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MergeDialog(object):
    def setupUi(self, MergeDialog):
        MergeDialog.setObjectName(_fromUtf8("MergeDialog"))
        MergeDialog.resize(835, 778)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MergeDialog.sizePolicy().hasHeightForWidth())
        MergeDialog.setSizePolicy(sizePolicy)
        MergeDialog.setMinimumSize(QtCore.QSize(0, 0))
        self.verticalLayout_4 = QtGui.QVBoxLayout(MergeDialog)
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.Diffs = QtGui.QWidget(MergeDialog)
        self.Diffs.setObjectName(_fromUtf8("Diffs"))
        self.verticalLayout = QtGui.QVBoxLayout(self.Diffs)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.Diffs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.branchToMergeLabel = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.branchToMergeLabel.sizePolicy().hasHeightForWidth())
        self.branchToMergeLabel.setSizePolicy(sizePolicy)
        self.branchToMergeLabel.setObjectName(_fromUtf8("branchToMergeLabel"))
        self.horizontalLayout.addWidget(self.branchToMergeLabel)
        self.branchToMergeBox = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.branchToMergeBox.sizePolicy().hasHeightForWidth())
        self.branchToMergeBox.setSizePolicy(sizePolicy)
        self.branchToMergeBox.setMaximumSize(QtCore.QSize(300, 1000))
        self.branchToMergeBox.setObjectName(_fromUtf8("branchToMergeBox"))
        self.horizontalLayout.addWidget(self.branchToMergeBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.viewChangesButton = QtGui.QPushButton(self.groupBox)
        self.viewChangesButton.setObjectName(_fromUtf8("viewChangesButton"))
        self.horizontalLayout.addWidget(self.viewChangesButton)
        self.mergeButton = QtGui.QToolButton(self.groupBox)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/merge-24.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mergeButton.setIcon(icon)
        self.mergeButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.mergeButton.setObjectName(_fromUtf8("mergeButton"))
        self.horizontalLayout.addWidget(self.mergeButton)
        self.verticalLayout.addWidget(self.groupBox)
        self.splitterChanges = QtGui.QSplitter(self.Diffs)
        self.splitterChanges.setOrientation(QtCore.Qt.Horizontal)
        self.splitterChanges.setObjectName(_fromUtf8("splitterChanges"))
        self.changesTree = QtGui.QTreeWidget(self.splitterChanges)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.changesTree.sizePolicy().hasHeightForWidth())
        self.changesTree.setSizePolicy(sizePolicy)
        self.changesTree.setMinimumSize(QtCore.QSize(200, 200))
        self.changesTree.setMaximumSize(QtCore.QSize(232131, 321321))
        self.changesTree.setAlternatingRowColors(True)
        self.changesTree.setUniformRowHeights(True)
        self.changesTree.setObjectName(_fromUtf8("changesTree"))
        self.splitter = QtGui.QSplitter(self.splitterChanges)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.attributesTable = QtGui.QTableWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attributesTable.sizePolicy().hasHeightForWidth())
        self.attributesTable.setSizePolicy(sizePolicy)
        self.attributesTable.setMinimumSize(QtCore.QSize(250, 100))
        self.attributesTable.setMaximumSize(QtCore.QSize(1000, 150))
        self.attributesTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.attributesTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.attributesTable.setProperty("showDropIndicator", False)
        self.attributesTable.setDragDropOverwriteMode(False)
        self.attributesTable.setAlternatingRowColors(False)
        self.attributesTable.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.attributesTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.attributesTable.setShowGrid(True)
        self.attributesTable.setGridStyle(QtCore.Qt.DotLine)
        self.attributesTable.setWordWrap(False)
        self.attributesTable.setObjectName(_fromUtf8("attributesTable"))
        self.attributesTable.setColumnCount(4)
        self.attributesTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        item.setFont(font)
        item.setBackground(QtGui.QColor(0, 0, 0, 0))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.attributesTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter | QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.attributesTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.attributesTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter | QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.attributesTable.setHorizontalHeaderItem(3, item)
        self.attributesTable.horizontalHeader().setCascadingSectionResizes(True)
        self.attributesTable.horizontalHeader().setDefaultSectionSize(135)
        self.attributesTable.horizontalHeader().setMinimumSectionSize(30)
        self.attributesTable.horizontalHeader().setStretchLastSection(True)
        self.attributesTable.verticalHeader().setVisible(False)
        self.attributesTable.verticalHeader().setCascadingSectionResizes(False)
        self.attributesTable.verticalHeader().setStretchLastSection(False)
        self.widget = QtGui.QWidget(self.splitter)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_12.setMargin(0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_10 = QtGui.QLabel(self.widget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_11.addWidget(self.label_10)
        self.showOursCheck = QtGui.QCheckBox(self.widget)
        self.showOursCheck.setChecked(True)
        self.showOursCheck.setObjectName(_fromUtf8("showOursCheck"))
        self.horizontalLayout_11.addWidget(self.showOursCheck)
        self.showTheirsCheck = QtGui.QCheckBox(self.widget)
        self.showTheirsCheck.setChecked(True)
        self.showTheirsCheck.setObjectName(_fromUtf8("showTheirsCheck"))
        self.horizontalLayout_11.addWidget(self.showTheirsCheck)
        self.showOriginCheck = QtGui.QCheckBox(self.widget)
        self.showOriginCheck.setChecked(True)
        self.showOriginCheck.setObjectName(_fromUtf8("showOriginCheck"))
        self.horizontalLayout_11.addWidget(self.showOriginCheck)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_11.addWidget(self.label_4)
        self.baseMapCombo = QtGui.QComboBox(self.widget)
        self.baseMapCombo.setObjectName(_fromUtf8("baseMapCombo"))
        self.baseMapCombo.addItem(_fromUtf8(""))
        self.baseMapCombo.addItem(_fromUtf8(""))
        self.baseMapCombo.addItem(_fromUtf8(""))
        self.horizontalLayout_11.addWidget(self.baseMapCombo)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.zoomButton = QtGui.QToolButton(self.widget)
        self.zoomButton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/zoom-extent.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomButton.setIcon(icon1)
        self.zoomButton.setObjectName(_fromUtf8("zoomButton"))
        self.horizontalLayout_11.addWidget(self.zoomButton)
        self.verticalLayout_12.addLayout(self.horizontalLayout_11)
        self.canvasWidget = QtGui.QWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canvasWidget.sizePolicy().hasHeightForWidth())
        self.canvasWidget.setSizePolicy(sizePolicy)
        self.canvasWidget.setMinimumSize(QtCore.QSize(0, 300))
        self.canvasWidget.setObjectName(_fromUtf8("canvasWidget"))
        self.verticalLayout_12.addWidget(self.canvasWidget)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.verticalLayout_12.addLayout(self.horizontalLayout_14)
        self.verticalLayout.addWidget(self.splitterChanges)
        self.verticalLayout_4.addWidget(self.Diffs)
        self.buttonBox = QtGui.QDialogButtonBox(MergeDialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_4.addWidget(self.buttonBox)

        self.retranslateUi(MergeDialog)
        QtCore.QMetaObject.connectSlotsByName(MergeDialog)

    def retranslateUi(self, MergeDialog):
        MergeDialog.setWindowTitle(_translate("MergeDialog", "Merge", None))
        self.groupBox.setTitle(_translate("MergeDialog", "Merge from", None))
        self.branchToMergeLabel.setText(_translate("MergeDialog", "Branch to merge onto current one:", None))
        self.viewChangesButton.setText(_translate("MergeDialog", "View changes before merging >>", None))
        self.mergeButton.setText(_translate("MergeDialog", "Merge", None))
        self.changesTree.headerItem().setText(0, _translate("MergeDialog", "List of Changes", None))
        self.attributesTable.setSortingEnabled(True)
        item = self.attributesTable.horizontalHeaderItem(0)
        item.setText(_translate("MergeDialog", "ATTRIBUTES", None))
        item = self.attributesTable.horizontalHeaderItem(1)
        item.setText(_translate("MergeDialog", "Local", None))
        item = self.attributesTable.horizontalHeaderItem(2)
        item.setText(_translate("MergeDialog", "To merge", None))
        item = self.attributesTable.horizontalHeaderItem(3)
        item.setText(_translate("MergeDialog", "Common ancestor", None))
        self.label_10.setText(_translate("MergeDialog", "Show:", None))
        self.showOursCheck.setText(_translate("MergeDialog", "Local", None))
        self.showTheirsCheck.setText(_translate("MergeDialog", "To Merge", None))
        self.showOriginCheck.setText(_translate("MergeDialog", "Common ancestor", None))
        self.label_4.setText(_translate("MergeDialog", "Base Map:", None))
        self.baseMapCombo.setItemText(0, _translate("MergeDialog", "None", None))
        self.baseMapCombo.setItemText(1, _translate("MergeDialog", "OpenStreetMap", None))
        self.baseMapCombo.setItemText(2, _translate("MergeDialog", "Google Maps", None))

import geogigclient_resources_rc
