# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'navigatordialog.ui'
#
# Created: Mon Mar 02 07:31:35 2015
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_NavigatorDialog(object):
    def setupUi(self, NavigatorDialog):
        NavigatorDialog.setObjectName(_fromUtf8("NavigatorDialog"))
        NavigatorDialog.resize(945, 611)
        self.verticalLayout_7 = QtGui.QVBoxLayout(NavigatorDialog)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.newRepoButton = QtGui.QToolButton(NavigatorDialog)
        self.newRepoButton.setMaximumSize(QtCore.QSize(150, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/new-repo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newRepoButton.setIcon(icon)
        self.newRepoButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.newRepoButton.setAutoRaise(False)
        self.newRepoButton.setObjectName(_fromUtf8("newRepoButton"))
        self.horizontalLayout.addWidget(self.newRepoButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.filterWidget = QtGui.QWidget(NavigatorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterWidget.sizePolicy().hasHeightForWidth())
        self.filterWidget.setSizePolicy(sizePolicy)
        self.filterWidget.setMinimumSize(QtCore.QSize(100, 0))
        self.filterWidget.setObjectName(_fromUtf8("filterWidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.filterWidget)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.filterButton = QtGui.QToolButton(self.filterWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterButton.sizePolicy().hasHeightForWidth())
        self.filterButton.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/filter.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.filterButton.setIcon(icon1)
        self.filterButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.filterButton.setAutoRaise(True)
        self.filterButton.setObjectName(_fromUtf8("filterButton"))
        self.horizontalLayout_3.addWidget(self.filterButton)
        self.clearFilterButton = QtGui.QToolButton(self.filterWidget)
        self.clearFilterButton.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/Close.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearFilterButton.setIcon(icon2)
        self.clearFilterButton.setIconSize(QtCore.QSize(10, 10))
        self.clearFilterButton.setAutoRaise(True)
        self.clearFilterButton.setObjectName(_fromUtf8("clearFilterButton"))
        self.horizontalLayout_3.addWidget(self.clearFilterButton)
        self.horizontalLayout.addWidget(self.filterWidget)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.splitter = QtGui.QSplitter(NavigatorDialog)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.leftWidget = QtGui.QWidget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftWidget.sizePolicy().hasHeightForWidth())
        self.leftWidget.setSizePolicy(sizePolicy)
        self.leftWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.leftWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leftWidget.setObjectName(_fromUtf8("leftWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.leftWidget)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.filterBox = QtGui.QLineEdit(self.leftWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterBox.sizePolicy().hasHeightForWidth())
        self.filterBox.setSizePolicy(sizePolicy)
        self.filterBox.setMinimumSize(QtCore.QSize(428, 26))
        self.filterBox.setMaximumSize(QtCore.QSize(10000, 1000))
        self.filterBox.setObjectName(_fromUtf8("filterBox"))
        self.horizontalLayout_4.addWidget(self.filterBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.repoTree = QtGui.QTreeWidget(self.leftWidget)
        self.repoTree.setMinimumSize(QtCore.QSize(0, 0))
        self.repoTree.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.repoTree.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.repoTree.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.repoTree.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.repoTree.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.repoTree.setUniformRowHeights(True)
        self.repoTree.setObjectName(_fromUtf8("repoTree"))
        self.repoTree.headerItem().setText(0, _fromUtf8("1"))
        self.repoTree.header().setVisible(False)
        self.repoTree.header().setStretchLastSection(False)
        self.verticalLayout_3.addWidget(self.repoTree)
        self.verticalLayout_5.addWidget(self.leftWidget)
        self.statusWidget = QtGui.QWidget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusWidget.sizePolicy().hasHeightForWidth())
        self.statusWidget.setSizePolicy(sizePolicy)
        self.statusWidget.setMinimumSize(QtCore.QSize(0, 32))
        self.statusWidget.setMaximumSize(QtCore.QSize(10000, 32))
        self.statusWidget.setObjectName(_fromUtf8("statusWidget"))
        self.verticalLayout_5.addWidget(self.statusWidget)
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tabWidget = QtGui.QTabWidget(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.repoDescription = QtGui.QTextBrowser(self.tab)
        self.repoDescription.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.repoDescription.sizePolicy().hasHeightForWidth())
        self.repoDescription.setSizePolicy(sizePolicy)
        self.repoDescription.setMinimumSize(QtCore.QSize(450, 400))
        self.repoDescription.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.repoDescription.setFrameShape(QtGui.QFrame.StyledPanel)
        self.repoDescription.setFrameShadow(QtGui.QFrame.Sunken)
        self.repoDescription.setObjectName(_fromUtf8("repoDescription"))
        self.verticalLayout_6.addWidget(self.repoDescription)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.versionsContainer = QtGui.QWidget(self.tab_2)
        self.versionsContainer.setObjectName(_fromUtf8("versionsContainer"))
        self.verticalLayout = QtGui.QVBoxLayout(self.versionsContainer)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.versionsWidget = QtGui.QWidget(self.versionsContainer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.versionsWidget.sizePolicy().hasHeightForWidth())
        self.versionsWidget.setSizePolicy(sizePolicy)
        self.versionsWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.versionsWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.versionsWidget.setObjectName(_fromUtf8("versionsWidget"))
        self.verticalLayout.addWidget(self.versionsWidget)
        self.verticalLayout_2.addWidget(self.versionsContainer)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.repoWidget = QtGui.QWidget(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.repoWidget.sizePolicy().hasHeightForWidth())
        self.repoWidget.setSizePolicy(sizePolicy)
        self.repoWidget.setMinimumSize(QtCore.QSize(0, 32))
        self.repoWidget.setMaximumSize(QtCore.QSize(10000, 32))
        self.repoWidget.setObjectName(_fromUtf8("repoWidget"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.repoWidget)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.branchLabel = QtGui.QLabel(self.repoWidget)
        self.branchLabel.setObjectName(_fromUtf8("branchLabel"))
        self.horizontalLayout_8.addWidget(self.branchLabel)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.openButton = QtGui.QToolButton(self.repoWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openButton.sizePolicy().hasHeightForWidth())
        self.openButton.setSizePolicy(sizePolicy)
        self.openButton.setMinimumSize(QtCore.QSize(32, 0))
        self.openButton.setMaximumSize(QtCore.QSize(16777215, 1000))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/open-repo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openButton.setIcon(icon3)
        self.openButton.setIconSize(QtCore.QSize(16, 16))
        self.openButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.openButton.setAutoRaise(False)
        self.openButton.setObjectName(_fromUtf8("openButton"))
        self.horizontalLayout_8.addWidget(self.openButton)
        self.verticalLayout_4.addWidget(self.repoWidget)
        self.placeholderWidget = QtGui.QWidget(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.placeholderWidget.sizePolicy().hasHeightForWidth())
        self.placeholderWidget.setSizePolicy(sizePolicy)
        self.placeholderWidget.setMinimumSize(QtCore.QSize(0, 32))
        self.placeholderWidget.setMaximumSize(QtCore.QSize(16777215, 32))
        self.placeholderWidget.setObjectName(_fromUtf8("placeholderWidget"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.placeholderWidget)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_4.addWidget(self.placeholderWidget)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.downloadButton = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downloadButton.sizePolicy().hasHeightForWidth())
        self.downloadButton.setSizePolicy(sizePolicy)
        self.downloadButton.setMinimumSize(QtCore.QSize(0, 32))
        self.downloadButton.setMaximumSize(QtCore.QSize(16777215, 32))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/download-repo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downloadButton.setIcon(icon4)
        self.downloadButton.setFlat(False)
        self.downloadButton.setObjectName(_fromUtf8("downloadButton"))
        self.horizontalLayout_7.addWidget(self.downloadButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.verticalLayout_7.addWidget(self.splitter)

        self.retranslateUi(NavigatorDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(NavigatorDialog)

    def retranslateUi(self, NavigatorDialog):
        NavigatorDialog.setWindowTitle(_translate("NavigatorDialog", "GeoGig Navigator", None))
        self.newRepoButton.setText(_translate("NavigatorDialog", "New Repository", None))
        self.filterButton.setText(_translate("NavigatorDialog", "Filter by...", None))
        self.filterBox.setPlaceholderText(_translate("NavigatorDialog", " Filter Repositories", None))
        self.repoTree.headerItem().setText(1, _translate("NavigatorDialog", "2", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("NavigatorDialog", "Repository Summary", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("NavigatorDialog", "Repository History", None))
        self.branchLabel.setText(_translate("NavigatorDialog", "branch", None))
        self.openButton.setText(_translate("NavigatorDialog", "Open Repository in QGIS ", None))
        self.downloadButton.setText(_translate("NavigatorDialog", "Download Repository", None))

import geogigclient_resources_rc
